
# This file controls the behavior of Supabase Edge Functions.
project_id = "nbjajaafqswspkytekun"

[functions.generate-market-queries]
verify_jwt = false

[functions.process-market-queries]
verify_jwt = false

[functions.scrape-research-urls]
verify_jwt = false

[functions.analyze-market]
verify_jwt = false

[functions.summarize-research-content]
verify_jwt = false
