
# This file controls the behavior of Supabase Edge Functions.
project_id = "nbjajaafqswspkytekun"

[functions.generate-market-queries]
verify_jwt = false

[functions.process-market-queries]
verify_jwt = false
