
project_id = "nbjajaafqswspkytekun"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
