// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apvcokzieoierrtcdnbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdmNva3ppZW9pZXJydGNkbmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDkzNDEsImV4cCI6MjA2MDk4NTM0MX0.0J9eonoORHoQwJySn5ImLLYCqrBSy8CNqkIIc4F-sdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);